global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.100.2:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.100.4:9100']

  - job_name: 'agario_exporter'
    static_configs:
      - targets: ['192.168.100.5:3000']
